export const users = [
  {
    id: 1,
    name: "Mark Dsuza",
    email: "markdsuza@gmail.com",
    url: "https://www.fishingtackleshop.com.au",
    satisfied: "no",
    rating: "N/A",
    feedback: "N/A",
    submit: {
      date: "31st Jan, 2024",
      time: "17:12:54",
    },
    avatar: "/images/avatar/avatar-9.jpg",
  },
  {
    id: 2,
    name: "Josef Jennyfer",
    email: "josefjennyfer@gmail.com",
    url: "https://www.fishingtackleshop.com.au",
    satisfied: "yes",
    rating: "N/A",
    feedback: "N/A",
    submit: {
      date: "31st Jan, 2024",
      time: "17:12:54",
    },
    avatar: "/images/avatar/avatar-10.jpg",
  },
  {
    id: 3,
    name: "Romeo D custa",
    email: "romeodcusta@gmail.com",
    url: "https://www.fishingtackleshop.com.au",
    satisfied: "no",
    rating: "N/A",
    feedback: "N/A",
    submit: {
      date: "31st Jan, 2024",
      time: "17:12:54",
    },
    avatar: "/images/avatar/avatar-1.jpg",
  },
  {
    id: 4,
    name: "Anald Donald",
    email: "janalddonald@gmail.com",
    url: "https://www.fishingtackleshop.com.au",
    satisfied: "somewhat",
    rating: "N/A",
    feedback: "N/A",
    submit: {
      date: "31st Jan, 2024",
      time: "17:12:54",
    },
    avatar: "/images/avatar/avatar-12.jpg",
  },
  {
    id: 5,
    name: "Vicky Patel",
    email: "vickypatel@gmail.com",
    url: "https://www.fishingtackleshop.com.au",
    satisfied: "yes",
    rating: "N/A",
    feedback: "N/A",
    submit: {
      date: "31st Jan, 2024",
      time: "17:12:54",
    },
    avatar: "/images/avatar/avatar-13.jpg",
  },
];